// Mocks generated by Mockito 5.1.0 from annotations
// in idt_messager/test/features/message_module/inbox/presenter/cubit/inbox_cubit_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:idt_messager/feature/message_module/domain/message_repository.dart'
    as _i2;
import 'package:idt_messager/feature/message_module/inbox/data/models/inbox_message_dto.dart'
    as _i4;
import 'package:idt_messager/feature/message_module/message_detail/data/models/message_detail_dto.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i2.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.InboxMessageDto>> fetchInboxMessages() =>
      (super.noSuchMethod(Invocation.method(#fetchInboxMessages, []),
              returnValue: Stream<List<_i4.InboxMessageDto>>.empty())
          as _i3.Stream<List<_i4.InboxMessageDto>>);
  @override
  _i3.Stream<List<_i5.MessageDetailDto>> messageDetailByGroupId(String? id) =>
      (super.noSuchMethod(Invocation.method(#messageDetailByGroupId, [id]),
              returnValue: Stream<List<_i5.MessageDetailDto>>.empty())
          as _i3.Stream<List<_i5.MessageDetailDto>>);
  @override
  _i3.Stream<_i5.MessageDetailDto> lastMessageFromSocketByGroupId(String? id) =>
      (super.noSuchMethod(
              Invocation.method(#lastMessageFromSocketByGroupId, [id]),
              returnValue: Stream<_i5.MessageDetailDto>.empty())
          as _i3.Stream<_i5.MessageDetailDto>);
  @override
  _i3.Stream<bool> sendMessage({String? message, String? id}) =>
      (super.noSuchMethod(
          Invocation.method(#sendMessage, [], {#message: message, #id: id}),
          returnValue: Stream<bool>.empty()) as _i3.Stream<bool>);
  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(Invocation.method(#dispose, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
